# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  profiles:
    active: native
  application:
     name: dummy-service-number-2  # Service registers under this name
